name: my app
on:
  push:
    paths:
      - '!README.md'
      - '!documents/**'
      - '**.tsx'
    # branches: [master]
    branches:
      - 'master'
      - 'release/**'
      - '!dev/**'
    workflows_dispath:
jobs:
  test-github-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello my app, to day is $TODAY
