name: my app
on:
  push:
    branches: [master]
jobs:
  test-github-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello my app
